# Generated by Django 4.2.3 on 2023-07-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resorts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skiresort',
            old_name='conitnent',
            new_name='continent',
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='average_snowfall',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='base_altitude',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='chairlifts',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='peak_altitude',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='skiiable_acreage',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='trails',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
