# Generated by Django 4.2.3 on 2024-01-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resorts', '0002_rename_conitnent_skiresort_continent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skiresort',
            name='weather_data',
            field=models.JSONField(null=True),
        ),
    ]
